show_chart:
  fields:
    device_id: &device_id
      required: true
      selector:
        device:
          integration: lametric_hass_local
    data:
      required: true
      example: "[1,2,3,4,5,4,3,2,1]"
      selector:
        object:
    sound: &sound
      required: false
      selector:
        select:
          options:
            - "alarm1"
            - "alarm2"
            - "alarm3"
            - "alarm4"
            - "alarm5"
            - "alarm6"
            - "alarm7"
            - "alarm8"
            - "alarm9"
            - "alarm10"
            - "alarm11"
            - "alarm12"
            - "alarm13"
            - "bicycle"
            - "car"
            - "cash"
            - "cat"
            - "dog"
            - "dog2"
            - "energy"
            - "knock-knock"
            - "letter_email"
            - "lose1"
            - "lose2"
            - "negative1"
            - "negative2"
            - "negative3"
            - "negative4"
            - "negative5"
            - "notification"
            - "notification2"
            - "notification3"
            - "notification4"
            - "open_door"
            - "positive1"
            - "positive2"
            - "positive3"
            - "positive4"
            - "positive5"
            - "positive6"
            - "statistic"
            - "thunder"
            - "water1"
            - "water2"
            - "win"
            - "win2"
            - "wind"
            - "wind_short"
          translation_key: sound
    cycles: &cycles
      required: false
      default: 1
      selector:
        number:
          min: 0
          max: 10
          mode: slider
    icon_type: &icon_type
      required: false
      default: "none"
      selector:
        select:
          mode: dropdown
          options:
            - "none"
            - "info"
            - "alert"
          translation_key: icon_type
    priority: &priority
      required: false
      default: "info"
      selector:
        select:
          mode: dropdown
          options:
            - "info"
            - "warning"
            - "critical"
          translation_key: priority
show_message:
  fields:
    device_id: *device_id
    message:
      required: true
      selector:
        text:
    icon:
      required: false
      selector:
        text:
    sound: *sound
    cycles: *cycles
    icon_type: *icon_type
    priority: *priority
start_stream:
  fields:
    device_id: *device_id
    config:
      required: true
      example: "
        {
          'canvas': {
              'fill_type': '[scale|tile]',
              'render_mode': '[pixel|triangle]',
              'post_process': {
                  'type': '[none|effect]',
                  'params': {
                      'effect_type': 'fading_pixels',
                      'effect_params': {
                          'smooth': true,
                          'pixel_fill': 1,
                          'fade_speed': 0.005,
                          'pixel_base': 0.05
                      }
                  }
              }
          }
        }"
      selector:
        object:
stop_stream:
  fields:
    device_id: *device_id
send_stream_data:
  fields:
    device_id: *device_id
    session_id:
      required: true
      selector:
        text:
    rgb_data:
      required: true
      example: "[[255,0,0],[0,255,0],[0,0,255],...]"
      selector:
        object:
set_screensaver:
  fields:
    device_id: *device_id
    enabled:
      required: true
      selector:
        boolean:
    mode:
      required: false
      default: "when_dark"
      selector:
        select:
          mode: dropdown
          options:
            - "when_dark"
            - "time_based"
          translation_key: screensaver_mode
    mode_params:
      required: false
      example: "{enabled: true, start_time: '2000-01-01T22:00:00', end_time: '2000-01-01T08:00:00'}"
      selector:
        object:
